// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://soqvdylpdxkwehemjtyc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvcXZkeWxwZHhrd2VoZW1qdHljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNzMwNTEsImV4cCI6MjA2NDk0OTA1MX0.SfxfnutkocffOCB54AjOAlGJGdp95Pmec2n-E0_GT5E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);